# Generated by Django 4.2.6 on 2023-10-22 12:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Общий отзыв",
                "verbose_name_plural": "Общие отзывы",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Метрика",
                "verbose_name_plural": "Метрики",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="static/photos", verbose_name="Фото"),
        ),
        migrations.CreateModel(
            name="WaitForReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
                ),
                (
                    "from_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wait_for_review_from_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи, которые должны дать обратную связь",
                    ),
                ),
                (
                    "to_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wait_for_review_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, который запросил обратную связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ожидание обратной связи",
                "verbose_name_plural": "Ожидания обратных связей",
            },
        ),
        migrations.CreateModel(
            name="FeedbackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "score_tone",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Тональность оценки",
                    ),
                ),
                ("score", models.IntegerField(default=5, verbose_name="Оценка")),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_items",
                        to="api.feedback",
                        verbose_name="Общий отзыв",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.metric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="FeedbackForUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
                (
                    "score_tone",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Тональность оценки",
                    ),
                ),
                ("is_reviewed_by_gpt", models.BooleanField(default=False)),
                (
                    "feedbacks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="feedbacks_for_user",
                        to="api.feedback",
                        verbose_name="Отзыв об одном сотруднике",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedback",
            name="from_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_from_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_to_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="feedback_viewed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_viewed",
                to="api.feedback",
                verbose_name="Просмотренные отзывы",
            ),
        ),
    ]
