# Generated by Django 4.2.6 on 2023-10-21 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Отдел", "verbose_name_plural": "Отделы"},
        ),
    ]
