# Generated by Django 4.2.6 on 2023-10-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_feedback_from_user_alter_feedback_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/photos", verbose_name="Фото"
            ),
        ),
    ]
