# Generated by Django 4.2.6 on 2023-10-21 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="should_give_feedback_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Должен дать обратную связь следующим людям",
            ),
        ),
    ]
