# Generated by Django 4.2.6 on 2023-10-21 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_user_should_give_feedback_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="should_give_feedback_to",
            field=models.ManyToManyField(
                blank=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Должен дать обратную связь следующим людям",
            ),
        ),
    ]
