# Generated by Django 4.2.6 on 2023-10-21 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_user_should_give_feedback_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="should_give_feedback_to",
        ),
        migrations.CreateModel(
            name="WaitForReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "to_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wait_for_review_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, который запросил обратную связь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="should_give_feedback_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_users",
                to="api.waitforreview",
                verbose_name="Должен дать обратную связь",
            ),
        ),
    ]
