# Generated by Django 4.2.6 on 2023-10-21 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_user_should_give_feedback_to_waitforreview_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitforreview",
            options={
                "verbose_name": "Ожидание обратной связи",
                "verbose_name_plural": "Ожидания обратных связей",
            },
        ),
    ]
