# Generated by Django 4.2.6 on 2023-10-21 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_waitforreview_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="should_give_feedback_to",
        ),
        migrations.AddField(
            model_name="waitforreview",
            name="from_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="wait_for_review_from_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи, которые должны дать обратную связь",
            ),
        ),
    ]
