# Generated by Django 4.2.6 on 2023-10-22 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_feedback_text_alter_feedbackitem_score_tone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="score_tone",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Тональность оценки",
            ),
        ),
    ]
