# Generated by Django 4.2.6 on 2023-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_feedback_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="created_at",
        ),
        migrations.CreateModel(
            name="FeedbackForUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "feedbacks",
                    models.ManyToManyField(
                        related_name="feedbacks_for_user",
                        to="api.feedback",
                        verbose_name="Отзыв об одном сотруднике",
                    ),
                ),
            ],
        ),
    ]
