# Generated by Django 4.2.6 on 2023-10-22 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_feedbackforuser_feedbacks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="score",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="score_tone",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="text",
        ),
        migrations.AddField(
            model_name="feedbackforuser",
            name="score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оценка",
            ),
        ),
        migrations.AddField(
            model_name="feedbackforuser",
            name="score_tone",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Тональность оценки",
            ),
        ),
        migrations.AddField(
            model_name="feedbackforuser",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
    ]
